"""add performance index for requests

Revision ID: 4cbe6f45094a
Revises: e93c85716e13
Create Date: 2026-07-20 16:51:47.234928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbe6f45094a'
down_revision: Union[str, Sequence[str], None] = 'e93c85716e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index('idx_requests_performance', 'requests', ['executor_id', 'status_id', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_requests_performance', table_name='requests')
    op.alter_column('requests', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
